apiVersion: apps/v1
kind: Deployment
metadata:
  name: ke-apachebeam-analysis-deployment
  labels:
    app: ke-apachebeam-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ke-apachebeam-analysis
  template:
    metadata:
      labels:
        app: ke-apachebeam-analysis
    spec:
      hostNetwork: true
      containers:
      - name: ke-apachebeam-analysis
        image: containerise/ke_apache_beam:ke_apache_analysis_v1.2
      - name: publisher
        image: penghuima/ke-testbeam:ke-v1.2
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/edge
        operator: Exists
        #command: ["/bin/sh"]
        #args: ["-c","./livedata --input 172.17.0.1:1883 --topic test && /bin/sh"]
